name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.0.5]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib install test.hxml --always

      - name: Compile test code
        run: haxelib run munit t
  subtree:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
#     - name: Create local changes
#       run: |
#         echo stupid >> test/text.txt
#     - name: Commit files
#       run: |
#         git add .
#         git commit -m "Add changes" -a
    - name: Subtree push
      uses: jbrooksuk/github-subtree-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'subtree_split_test'
        directory: './test'
