name: CI

on:
  push:
    branches:
      - master

jobs:
  unit_tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.0.5]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib install test.hxml --always

      - name: Compile test code
        run: haxelib run munit t
  npm-publish:
    needs: unit_tests
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    - name: Publish if version has been updated
      uses: pascalgn/npm-publish-action@master
      with: # All of theses inputs are optional
        tag_name: "%s"
        tag_message: "%s"
        commit_pattern: ".*"
      env: # More info about the environment variables in the README
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # You need to set this in your repo settings
  subtree:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
#     - name: Create local changes
#       run: |
#         echo stupid >> test/text.txt
#     - name: Commit files
#       run: |
#         git add .
#         git commit -m "Add changes" -a
    - name: Subtree push
      run: |
        git subtree split --prefix=test -b subtree_split_test_2
        git push origin subtree_split_test_2
