name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        haxe: [4.0.5]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{ matrix.haxe }}
      - run: haxe -version
      - run: haxelib install test.hxml --always

      - name: Compile test code
        run: haxelib run munit t
  subtree:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup git user
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action
    - name: Create local changes
      run: |
        echo stupid >> text.txt
    - name: Commit files
      run: |
        git add .
        git commit -m "Add changes" -a
    - name: Subtree Split
      run: |
        git subtree split --prefix=test subtree_split_test 
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'subtree_split_test'
